Repository leomaurodesenv/qasports-dataset-scripts, pull requests merged in 2025-07, with the labels that each got.

#34 refactor: rename 'gathering' module to 'crawler' for improved clarity
  .github/workflows/gathering-workflow.yml
  README.md
  output/americanfootball-links.csv
  output/baseball-links.csv
  output/basketball-links.csv
  output/f1-links.csv
  output/football-links.csv
  output/gymnastics-links.csv
  output/rugby-links.csv
  src/crawler/__init__.py
  src/crawler/module.py
  src/crawler/run.py
Labels: enhancement, good first issue

#36 feat: add labelling_llm (fixed)
  pyproject.toml
  src/labeling_llm/module.py
  src/labeling_llm/run.py
  uv.lock
Labels: enhancement

#37 fix: labeling llm
  README.md
  src/labeling_llm/__init__.py
  src/labeling_llm/module.py
  src/labeling_llm/run.py
  src/module.py
  uv.lock
Labels: enhancement, fix

#39 feat: add doc retriever
  experiments/doc_reader.py
  experiments/doc_retriever.py
  experiments/module.py
Labels: enhancement
